# ====================================================================================================================================
# @file       GetGyroBiasOffsets.srv
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 30th May 2022 5:29:26 pm
# @modified   Monday, 30th May 2022 5:51:00 pm
# @project    engineering-thesis
# @brief      Service message type describing a request-response model for asking an IMU sensor driver for reading bias offsets 
#             of gyro sensors of each axis
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

---

# Bias offsets of gyro sensor
velmwheel_imu_driver_msgs/GyroBiasOffsets offsets

# True if valid response data has been returned
bool success
# Human readable error message if success is @c false, else empty string.
string error_message
