# ====================================================================================================================================
# @file       Point2D.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Thursday, 31st March 2022 4:46:45 pm
# @modified   Wednesday, 25th May 2022 4:18:40 pm
# @project    engineering-thesis
# @brief      Auxiliary ROS message type describing a 2D point
#
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# X coordinate of the point
float64 x
# Y coordinate of the point
float64 y
