# ====================================================================================================================================
# @file       AccelerationBiasOffsets.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 30th May 2022 5:29:26 pm
# @modified   Monday, 30th May 2022 5:48:08 pm
# @project    engineering-thesis
# @brief      Message structure holding bias offsets of acceleration sensors of each axis
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Bias offset of the X axis' acceleration sensor in [m/s^2]
float64 x
# Bias offset of the Y axis' acceleration sensor in [m/s^2]
float64 y
# Bias offset of the Z axis' acceleration sensor in [m/s^2]
float64 z
