# ====================================================================================================================================
# @file       GyroBiasOffsets.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 30th May 2022 5:29:26 pm
# @modified   Monday, 30th May 2022 5:48:19 pm
# @project    engineering-thesis
# @brief      Message structure holding bias offsets of gyro sensors of each axis
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Bias offset of the X axis' gyro in [°/s]
float64 x
# Bias offset of the Y axis' gyro in [°/s]
float64 y
# Bias offset of the Z axis' gyro in [°/s]
float64 z
