# ====================================================================================================================================
# @file       GyroTemperatures.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 30th May 2022 5:29:26 pm
# @modified   Monday, 30th May 2022 5:50:02 pm
# @project    engineering-thesis
# @brief      Message structure holding temperatures of gyro sensors of each axis
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Temperature of the X axis' gyro in [°C]
float32 x
# Temperature of the Y axis' gyro in [°C]
float32 y
# Temperature of the Z axis' gyro in [°C]
float32 z
