# ====================================================================================================================================
# @file       GetDigitalFilter.srv
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 30th May 2022 5:29:26 pm
# @modified   Monday, 30th May 2022 5:56:08 pm
# @project    engineering-thesis
# @brief      Service message type describing a request-response model for asking an IMU sensor driver for reading current value
#             of the digital filter's constant
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

---

# ----------------------------------------------------------------
# Current filter constant
# 
# @see 'Układ elektroniczny do akwizycji danych z jednostki
#    inercyjnej za pośrednictwem EtherCAT', B. J. Kaczor, 2017, 
#    p. 26
# ----------------------------------------------------------------
uint16 filter

# True if valid response data has been returned
bool success
# Human readable error message if success is @c false, else empty string.
string error_message
