# ====================================================================================================================================
# @file       EncoderRaw.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Thursday, 28th April 2022 7:17:24 pm
# @modified   Wednesday, 25th May 2022 4:44:01 pm
# @project    engineering-thesis
# @brief      Interface representing set of measurements from the robot's wheel encoder
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Angle of the wheel in [rad]
float64 angle
# Angular velocity of the wheel in [rad/s]
float64 velocity
