# ====================================================================================================================================
# @file       Encoders.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Thursday, 28th April 2022 7:17:24 pm
# @modified   Wednesday, 25th May 2022 4:44:01 pm
# @project    engineering-thesis
# @brief      Interface representing set of measurements from the robot's wheel encoders
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Actual measurements
velmwheel_msgs/EncoderRaw[4] encoders
