# ====================================================================================================================================
# @file       WheelSetpoint.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Thursday, 28th April 2022 7:17:24 pm
# @modified   Wednesday, 25th May 2022 4:44:01 pm
# @project    engineering-thesis
# @brief      Interface providing speed for the robot's wheel
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Wheel-related measurements
float64[4] values
