# ====================================================================================================================================
# @file       WheelSetpoint.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Thursday, 28th April 2022 7:17:24 pm
# @modified   Wednesday, 25th May 2022 4:44:01 pm
# @project    engineering-thesis
# @brief      Interface providing measurement related to robot's wheel
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Identifier of the encoder
uint8 id
# Wheel-related measurement
float64 value
