# ====================================================================================================================================
# @file       WheelID.msg
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Thursday, 28th April 2022 7:17:24 pm
# @modified   Wednesday, 25th May 2022 4:44:01 pm
# @project    engineering-thesis
# @brief      Interface providing definitions of wheels identifiers
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Possible wheel IDs
uint8 REAR_LEFT   = 0
uint8 REAR_RIGHT  = 1
uint8 FRONT_LEFT  = 2
uint8 FRONT_RIGHT = 3
# Number of wheels
uint8 NUM = 4