# ====================================================================================================================================
# @file       ChangeMode.srv
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Friday, 1st April 2022 2:04:16 pm
# @modified   Wednesday, 25th May 2022 4:44:01 pm
# @project    engineering-thesis
# @brief      Auxiliary service message type describing a request-response model for asking a global-localization mode changing the mode
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Possible modes
uint8 IDLE             = 0
uint8 LOCALIZATION_STD = 1
uint8 LOCALIZATION_ICP = 2

# Mode to be set
uint8 mode
---
# Servic'e status (@c true on success)
bool succeeded
# (Optional) Error reaosn
string reason
