# ====================================================================================================================================
# @file       Enable.srv
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 13th June 2022 8:39:16 pm
# @modified   Friday, 1st July 2022 4:31:00 pm
# @project    engineering-thesis
# @brief      Service message type describing a request-response model for asking a base driver for changing it's state
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

# Flag indicating target state of the driver
bool enable

---

# True if service has been sucesfully served
bool success
# Human readable error message if success is @c false, else empty string.
string error_message
