# ====================================================================================================================================
# @file       ResetFailure.srv
# @author     Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @maintainer Krzysztof Pierczyk (krzysztof.pierczyk@gmail.com)
# @date       Monday, 13th June 2022 8:39:16 pm
# @modified   Monday, 13th June 2022 8:40:12 pm
# @project    engineering-thesis
# @brief      Service message type describing a request-response model for asking a base driver for resetting fault of 
#             servidrivers
#    
#    
# @copyright Krzysztof Pierczyk © 2022
# ====================================================================================================================================

---

# True if service has been sucesfully served
bool success
# Human readable error message if success is @c false, else empty string.
string error_message
